[package]
name = "jemalloc_pprof"
description = "CPU and memory profiling tools."
version = "0.1.0"
edition = "2021"
publish = true
license = "Apache-2.0"
authors = [
    "Frederic Branczyk <frederic.branczyk@polarsignals.com>",
    "Brennan Vincent <brennan@materialize.com>",
]

[dependencies]
anyhow = "1.0.66"
backtrace = "0.3.66"
flate2 = "1.0.24"
libc = "0.2.138"
once_cell = "1.16.0"
prost = { version = "0.11.3", features = ["no-recursion-limit"] }
tempfile = "3.2.0"
tikv-jemalloc-ctl = { version = "0.5.0", features = ["use_std"] }
tracing = "0.1.37"
tokio = { version = "1.32.0", features = ["time", "sync"] }
paste = "1.0.11"
num = "0.4.0"
